-- Applied to Supabase project nnhiauutailohjseajmf through the Supabase MCP on 2026-09-11.
-- Do not run this legacy manual setup file.
-- The reviewed, idempotent repository migration is:
-- supabase/migrations/20260911000000_order_lifecycle.sql
