'use client'

import { useDeferredValue, useState } from 'react'
import Link from 'next/link'
import useSWR from 'swr'
import { ChevronLeft, ChevronRight, Search, Users } from 'lucide-react'
import type { AdminUserListItem } from '@/lib/admin/operations-server'

const fetcher = async (url: string) => {
  const response = await fetch(url, { cache: 'no-store' })
  if (!response.ok) throw new Error('request_failed')
  return response.json() as Promise<{ users: AdminUserListItem[]; page: number; pages: number; total: number }>
}

export function CustomersTab() {
  const [search, setSearch] = useState('')
  const deferredSearch = useDeferredValue(search)
  const [status, setStatus] = useState('all')
  const [tier, setTier] = useState('all')
  const [sort, setSort] = useState('joined')
  const [page, setPage] = useState(1)
  const query = new URLSearchParams({ q: deferredSearch, status, tier, sort, page: String(page), limit: '20' })
  const { data, error, isLoading } = useSWR(`/api/admin/users?${query}`, fetcher, { keepPreviousData: true })

  function resetPage() { setPage(1) }

  return <div className="flex flex-col gap-6" dir="rtl"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-bold">إدارة العملاء</h1><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{data?.total || 0} عميل</span></div><p className="mt-2 text-sm text-muted-foreground">بحث وتصفية حقيقية من الخادم مع صفحة مستقلة لكل مستخدم.</p></div></header>
    <section className="grid gap-3 rounded-3xl bg-card p-4 ring-1 ring-border md:grid-cols-[1fr_repeat(3,minmax(9rem,auto))]"><label className="relative"><span className="sr-only">بحث</span><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => { setSearch(event.target.value); resetPage() }} placeholder="الاسم أو البريد أو الهاتف" className="w-full rounded-xl border border-border bg-background py-2.5 ps-10 pe-3 text-sm outline-none focus:border-primary" /></label><select value={status} onChange={(event) => { setStatus(event.target.value); resetPage() }} className="rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="all">كل الحالات</option><option value="active">نشط</option><option value="suspended">معلّق</option><option value="pending">قيد المراجعة</option></select><select value={tier} onChange={(event) => { setTier(event.target.value); resetPage() }} className="rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="all">كل الفئات</option><option value="Regular">Regular</option><option value="Gold">Gold</option><option value="Platinum">Platinum</option><option value="VIP">VIP</option></select><select value={sort} onChange={(event) => { setSort(event.target.value); resetPage() }} className="rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="joined">الأحدث انضمامًا</option><option value="orders">الأكثر طلبًا</option><option value="spent">الأعلى إنفاقًا</option><option value="activity">آخر نشاط</option></select></section>
    {error ? <div className="rounded-3xl bg-card p-8 text-center text-sm text-destructive ring-1 ring-border">تعذر تحميل العملاء. تحقق من جلسة الإدارة ثم حاول مجددًا.</div> : <div className="overflow-hidden rounded-3xl bg-card ring-1 ring-border"><div className="overflow-x-auto"><table className="w-full min-w-[58rem] text-sm"><thead className="bg-secondary text-xs text-muted-foreground"><tr><th className="px-5 py-4 text-start">العميل</th><th className="px-5 py-4 text-start">التواصل</th><th className="px-5 py-4 text-start">الحالة</th><th className="px-5 py-4 text-start">الفئة</th><th className="px-5 py-4 text-start">الطلبات</th><th className="px-5 py-4 text-start">المدفوع</th><th className="px-5 py-4 text-start">آخر نشاط</th><th className="px-5 py-4 text-end">التفاصيل</th></tr></thead><tbody>{isLoading && !data ? <tr><td colSpan={8} className="p-12 text-center text-muted-foreground">جاري التحميل…</td></tr> : data?.users.length ? data.users.map((user) => <tr key={user.id} className="border-t border-border hover:bg-secondary/50"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-secondary font-bold text-primary">{user.name.slice(0, 1).toUpperCase()}</span><div><p className="font-semibold">{user.name}</p><p className="mt-1 text-xs text-muted-foreground">منذ {new Date(user.joinedAt).toLocaleDateString('ar')}</p></div></div></td><td className="px-5 py-4"><p>{user.email}</p><p className="mt-1 text-xs text-muted-foreground">{user.phone || '—'}</p></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs ${user.status === 'suspended' ? 'bg-destructive/10 text-destructive' : 'bg-primary/10 text-primary'}`}>{user.status}</span></td><td className="px-5 py-4 font-semibold">{user.tier}</td><td className="px-5 py-4">{user.ordersCount}</td><td className="px-5 py-4 font-semibold">₪{(user.totalSpentMinor / 100).toLocaleString()}</td><td className="px-5 py-4 text-xs text-muted-foreground">{user.lastOrderAt ? new Date(user.lastOrderAt).toLocaleDateString('ar') : '—'}</td><td className="px-5 py-4 text-end"><Link href={`/admin/users/${user.id}`} className="inline-flex rounded-full border border-border px-4 py-2 text-xs font-bold hover:bg-secondary">فتح الملف</Link></td></tr>) : <tr><td colSpan={8} className="p-12 text-center text-muted-foreground"><Users className="mx-auto mb-3 size-8" />لا توجد نتائج مطابقة.</td></tr>}</tbody></table></div></div>}
    <footer className="flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">صفحة {data?.page || page} من {data?.pages || 1}</p><div className="flex gap-2"><button type="button" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={page <= 1} className="flex size-10 items-center justify-center rounded-full border border-border disabled:opacity-40"><ChevronRight className="size-4" /><span className="sr-only">السابق</span></button><button type="button" onClick={() => setPage((value) => Math.min(data?.pages || value, value + 1))} disabled={page >= (data?.pages || 1)} className="flex size-10 items-center justify-center rounded-full border border-border disabled:opacity-40"><ChevronLeft className="size-4" /><span className="sr-only">التالي</span></button></div></footer>
  </div>
}
