'use client'

import { useState } from 'react'
import Link from 'next/link'
import useSWR from 'swr'
import { ArrowRight, Loader2, MapPin, Save, ShieldBan, ShoppingBag, UserRound } from 'lucide-react'
import { orderStatusLabel, type OrderStatus } from '@/lib/orders/status'
import type { Json } from '@/lib/supabase/database.types'

type Detail = { profile: { id: string; email: string; display_name: string; username: string | null; phone: string | null; preferred_locale: string; avatar_url: string | null; status: string; tier: string; interested_in: string | null; admin_notes: string | null; created_at: string }; addresses: Array<{ id: string; label: string; kind: string; full_name: string; phone: string; company: string | null; street: string; address_line_2: string | null; city: string; state: string | null; country: string; postal_code: string | null; is_default: boolean }>; orders: Array<{ id: string; order_number: string; status: OrderStatus; total_minor: number; currency: string; payment_status: string; payment_method: string; tracking_number: string | null; carrier: string | null; created_at: string }>; payments: Array<{ id: string; order_id: string; from_status: string | null; to_status: string; amount_minor: number; currency: string; payment_method: string | null; changed_by: string | null; note: string | null; created_at: string }>; audit: Array<{ id?: Json; actor_id?: Json; action?: Json; entity_type?: Json; before_value?: Json; after_value?: Json; created_at?: Json }>; history: Array<{ id: string; order_id: string; to_status: OrderStatus; note: string | null; changed_by: string | null; created_at: string }> }
const fetcher = async (url: string) => { const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) throw new Error('request_failed'); return response.json() as Promise<Detail> }

export function AdminUserDetail({ userId }: { userId: string }) {
  const { data, error, isLoading, mutate } = useSWR(`/api/admin/users/${userId}`, fetcher)
  const [pending, setPending] = useState(false)
  const [message, setMessage] = useState('')
  if (isLoading) return <div className="flex min-h-[50vh] items-center justify-center gap-3 text-muted-foreground"><Loader2 className="size-5 animate-spin" />جاري تحميل ملف العميل…</div>
  if (error || !data) return <div className="rounded-3xl bg-card p-8 text-center text-destructive ring-1 ring-border">تعذر فتح ملف المستخدم أو لا تملك الصلاحية.</div>
  const { profile, addresses, orders, payments, audit, history } = data
  const activeOrders = orders.filter((order) => !['completed','cancelled'].includes(order.status)).length
  const completedOrders = orders.filter((order) => order.status === 'completed').length
  const paid = payments.filter((event) => event.to_status === 'paid').reduce((sum, event) => sum + event.amount_minor, 0)
  const refunded = payments.filter((event) => event.to_status === 'refunded').reduce((sum, event) => sum + event.amount_minor, 0)

  async function update(patch: Record<string, unknown>) { setPending(true); setMessage(''); const response = await fetch(`/api/admin/users/${userId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }); if (!response.ok) { setMessage('تعذر حفظ التحديث.'); setPending(false); return } await mutate(); setMessage('تم الحفظ بنجاح.'); setPending(false) }

  return <div className="flex flex-col gap-6" dir="rtl"><Link href="/admin" className="inline-flex w-fit items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowRight className="size-4" />العودة للوحة</Link><header className="flex flex-wrap items-start justify-between gap-5 rounded-3xl bg-card p-6 ring-1 ring-border"><div className="flex items-center gap-4"><span className="flex size-16 items-center justify-center rounded-full bg-secondary text-2xl font-bold text-primary">{profile.display_name.slice(0,1)}</span><div><h1 className="text-2xl font-bold">{profile.display_name}</h1><p className="mt-1 text-sm text-muted-foreground">{profile.email} · {profile.phone || 'بدون هاتف'}</p><p className="mt-1 text-xs text-muted-foreground">انضم {new Date(profile.created_at).toLocaleDateString('ar')} · اللغة {profile.preferred_locale}</p></div></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{profile.tier}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${profile.status === 'suspended' ? 'bg-destructive/10 text-destructive' : 'bg-secondary'}`}>{profile.status}</span><button type="button" disabled={pending} onClick={() => update({ status: profile.status === 'suspended' ? 'active' : 'suspended' })} className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-xs font-bold"><ShieldBan className="size-4" />{profile.status === 'suspended' ? 'إعادة التفعيل' : 'تعليق الحساب'}</button></div></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[['الطلبات',orders.length],['النشطة',activeOrders],['المكتملة',completedOrders],['المدفوع',`₪${(paid/100).toLocaleString()}`],['المسترد',`₪${(refunded/100).toLocaleString()}`],['متوسط الطلب',orders.length ? `₪${(orders.reduce((s,o)=>s+o.total_minor,0)/orders.length/100).toLocaleString()}` : '₪0']].map(([label,value]) => <div key={String(label)} className="rounded-2xl bg-card p-4 ring-1 ring-border"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-serif text-xl font-bold">{value}</p></div>)}</section>
    <ProfileEditor profile={profile} pending={pending} onSave={update} message={message} />
    <section className="rounded-3xl bg-card p-6 ring-1 ring-border"><h2 className="flex items-center gap-2 text-xl font-bold"><MapPin className="size-5 text-primary" />العناوين</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{addresses.map((address) => <article key={address.id} className="rounded-2xl bg-secondary p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">{address.label || address.kind}</h3>{address.is_default ? <span className="text-xs text-primary">افتراضي</span> : null}</div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{[address.full_name,address.company,address.street,address.address_line_2,address.city,address.state,address.country,address.postal_code].filter(Boolean).join('، ')}</p><p className="mt-2 text-sm">{address.phone}</p></article>)}</div></section>
    <section className="rounded-3xl bg-card p-6 ring-1 ring-border"><h2 className="flex items-center gap-2 text-xl font-bold"><ShoppingBag className="size-5 text-primary" />الطلبات</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[44rem] text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="py-3 text-start">الطلب</th><th className="py-3 text-start">التاريخ</th><th className="py-3 text-start">الحالة</th><th className="py-3 text-start">الدفع</th><th className="py-3 text-end">الإجمالي</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b border-border"><td className="py-4 font-mono">#{order.order_number}</td><td>{new Date(order.created_at).toLocaleDateString('ar')}</td><td>{orderStatusLabel(order.status,'ar')}</td><td>{order.payment_status}</td><td className="text-end font-bold">{new Intl.NumberFormat('en',{style:'currency',currency:order.currency}).format(order.total_minor/100)}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl bg-card p-6 ring-1 ring-border"><h2 className="text-xl font-bold">سجل المدفوعات</h2><ol className="mt-5 flex flex-col gap-4">{payments.map((event) => <li key={event.id} className="border-b border-border pb-4"><div className="flex justify-between gap-4"><p className="font-semibold">{event.from_status || 'بداية'} ← {event.to_status}</p><p className="font-bold">{new Intl.NumberFormat('en',{style:'currency',currency:event.currency}).format(event.amount_minor/100)}</p></div><p className="mt-1 text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString('ar')} · {event.payment_method || '—'}</p></li>)}</ol></section><section className="rounded-3xl bg-card p-6 ring-1 ring-border"><h2 className="text-xl font-bold">سجل النشاط</h2><ol className="mt-5 flex flex-col gap-4">{[...history.map((entry) => ({ id: entry.id, title: `حالة طلب: ${orderStatusLabel(entry.to_status,'ar')}`, date: entry.created_at })), ...audit.map((entry, index) => ({ id: String(entry.id || index), title: String(entry.action || 'admin_action'), date: String(entry.created_at || '') }))].sort((a,b)=>b.date.localeCompare(a.date)).map((entry) => <li key={entry.id} className="border-b border-border pb-4"><p className="font-semibold">{entry.title}</p><p className="mt-1 text-xs text-muted-foreground">{entry.date ? new Date(entry.date).toLocaleString('ar') : '—'}</p></li>)}</ol></section></div>
  </div>
}

function ProfileEditor({ profile, pending, onSave, message }: { profile: Detail['profile']; pending: boolean; onSave: (patch: Record<string, unknown>) => Promise<void>; message: string }) {
  const [tier, setTier] = useState(profile.tier)
  const [interestedIn, setInterestedIn] = useState(profile.interested_in || '')
  const [adminNotes, setAdminNotes] = useState(profile.admin_notes || '')
  return <section className="rounded-3xl bg-card p-6 ring-1 ring-border"><h2 className="flex items-center gap-2 text-xl font-bold"><UserRound className="size-5 text-primary" />البيانات والملاحظات الإدارية</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-sm">الفئة<select value={tier} onChange={(event)=>setTier(event.target.value)} className="rounded-xl border border-border bg-background px-3 py-2.5"><option>Regular</option><option>Gold</option><option>Platinum</option><option>VIP</option></select></label><label className="flex flex-col gap-2 text-sm">الاهتمامات<input value={interestedIn} onChange={(event)=>setInterestedIn(event.target.value)} className="rounded-xl border border-border bg-background px-3 py-2.5" /></label><label className="flex flex-col gap-2 text-sm">ملاحظات الإدارة<textarea value={adminNotes} onChange={(event)=>setAdminNotes(event.target.value)} rows={3} className="rounded-xl border border-border bg-background px-3 py-2.5" /></label></div><div className="mt-5 flex items-center justify-between gap-4">{message ? <p className="text-sm text-muted-foreground">{message}</p> : <span />}<button type="button" disabled={pending} onClick={() => onSave({ tier, interestedIn, adminNotes })} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60">{pending ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}حفظ الملف</button></div></section>
}
